# Generated by Django 4.2.25 on 2025-11-21 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0003_userinfo_user_id_alter_userinfo_username'),
        ('weightlog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weightlog',
            name='LogId',
        ),
        migrations.AlterField(
            model_name='weightlog',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='userInfo.userinfo', to_field='user_id'),
        ),
    ]
