# Generated by Django 4.2.25 on 2025-11-06 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='UserInfo',
        ),
    ]
