# Generated by Django 4.2.25 on 2025-11-21 07:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0002_rename_student_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
