# Generated by Django 5.2.8 on 2025-11-24 18:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userInfo', '0003_userinfo_user_id_alter_userinfo_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=32)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('expected_fields', models.JSONField(blank=True, default=list)),
                ('next_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='userInfo.userinfo', to_field='user_id')),
            ],
        ),
    ]
