# Generated by Django 4.2.25 on 2025-11-10 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userInfo', '0002_rename_student_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ActivityHour', models.DateTimeField()),
                ('StepTotal', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitness_records', to='userInfo.userinfo')),
            ],
        ),
    ]
