# Generated by Django 4.2.25 on 2025-11-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessRecord', '0002_alter_fitnessrecord_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnessrecord',
            name='StepTotal',
        ),
        migrations.AddField(
            model_name='fitnessrecord',
            name='AverageIntensity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='fitnessrecord',
            name='TotalIntensity',
            field=models.IntegerField(default=0),
        ),
    ]
