# Generated by Django 4.2.25 on 2025-11-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessRecord', '0003_remove_fitnessrecord_steptotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessrecord',
            name='activity_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fitnessrecord',
            name='duration_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
