# Generated by Django 4.2.25 on 2025-11-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessRecord', '0004_fitnessrecord_activity_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnessrecord',
            name='ActivityHour',
        ),
        migrations.RemoveField(
            model_name='fitnessrecord',
            name='AverageIntensity',
        ),
        migrations.RemoveField(
            model_name='fitnessrecord',
            name='TotalIntensity',
        ),
        migrations.AddField(
            model_name='fitnessrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
